DROP TABLE IF EXISTS T_PRODUCTS;

CREATE TABLE T_PRODUCTS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_NUMBER VARCHAR(50),
    PRODUCT_NAME VARCHAR(100),
    PRICE DOUBLE,
    QUANTITY INT
);